SUMMARY = "CodeSynthesis XSD C++/Tree header-only runtime library"
DESCRIPTION = "The libxsd headers required to compile code generated by \
CodeSynthesis' XSD binding compiler (xsdcxx). Installed into the target \
sysroot so that cross-compiled binaries pick them up."
HOMEPAGE = "https://www.codesynthesis.com/products/xsd/"

LICENSE = "GPL-2.0-only & FLOSSE"
LIC_FILES_CHKSUM = " \
    file://GPLv2;md5=eb723b61539feef013de476e68b5c50a \
    file://FLOSSE;md5=42d25a3b4b2b4178d3cb0f434fccfb68 \
    file://LICENSE;md5=79e31466c4d9f3a85f2f987c11ebcd83 \
"

# Same tarball as xsdcxx-native; we consume only the libxsd/xsd headers.
SRC_URI = "https://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd-4.0.0-x86_64-linux-gnu.tar.bz2"
SRC_URI[sha256sum] = "d01060cbf4b3a1e462a5c5ad1a5a6773b541766dbbb98e50c9efb8f2a2dd55b7"

S = "${UNPACKDIR}/xsd-4.0.0-x86_64-linux-gnu"

inherit allarch

do_configure[noexec] = "1"
do_compile[noexec] = "1"

NO_GENERIC_LICENSE[FLOSSE] = "FLOSSE"

do_install() {
    install -d ${D}${includedir}
    cp -a ${S}/libxsd/xsd ${D}${includedir}/
}

FILES:${PN} = "${includedir}/xsd"

# Header-only, no shared libraries or binaries.
ALLOW_EMPTY:${PN} = "1"
