SUMMARY = "RAUC update bundle for MissionDMX (verity format)"
DESCRIPTION = "Packages the built rootfs into a verity-format RAUC bundle \
signed with the classical RSA-4096 key generated by ./sign-images.sh. \
The bundle is emitted to DEPLOY_DIR_IMAGE/*.raucb and picked up by the \
top-level Makefile's 'publish' target, which additionally attaches a \
hybrid RSA + ML-DSA-65 CMS sidecar signature (sign-images.sh) and \
assembles build/updates/ for HTTP distribution. The sidecar is what \
gates unattended acceptance by mdmx-updater on the target; rauc install \
then re-verifies the embedded CMS on top."

# meta-rauc's sanity handler expects LICENSE to be set — MIT to match
# the rest of meta-custom.
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit bundle

# Verity is the current-recommended RAUC bundle format:
#   * Bundle body is a squashfs whose per-block hashes are covered by a
#     dm-verity hash tree, and the tree's root hash is the only thing
#     the CMS signature actually signs.
#   * On the target, `rauc install` mounts the squashfs directly through
#     verity, so tampering with any block after the signature check is
#     rejected at read time (not just at bundle-open time).
# system.conf refuses `plain` bundles, so switching this off would leave
# the target unable to install its own output.
RAUC_BUNDLE_FORMAT = "verity"

# Must match `[system] compatible=` in meta-custom/recipes-core/rauc/files/system.conf.
# RAUC refuses to install a bundle whose compatible string differs from the
# target's, so this string doubles as the "which platform is this update
# for" gate on the update server.
RAUC_BUNDLE_COMPATIBLE = "MissionDMX"

# ${DATETIME} expands to the build timestamp (YYYYMMDDhhmmss). This is
# what the client compares against /etc/mdmx-build-timestamp on the
# target to decide whether an update is newer. vardepsexclude keeps
# bitbake from busting the sstate cache every time the wall clock ticks.
RAUC_BUNDLE_VERSION = "${DATETIME}"
RAUC_BUNDLE_VERSION[vardepsexclude] = "DATETIME"
RAUC_BUNDLE_BUILD = "${DATETIME}"
RAUC_BUNDLE_BUILD[vardepsexclude] = "DATETIME"
RAUC_BUNDLE_DESCRIPTION = "MissionDMX firmware update"

RAUC_BUNDLE_SLOTS = "rootfs"
RAUC_SLOT_rootfs = "core-image-minimal"
RAUC_SLOT_rootfs[fstype] = "ext4"

# MDMX_KEYS_DIR is set in local.conf to the absolute path of the
# top-level keys/signing/ directory that sign-images.sh manages. The
# embedded RAUC signature uses only the RSA half of the hybrid pair;
# rauc(1) upstream doesn't yet accept multiple signers per bundle. The
# ML-DSA half rides along as a detached sidecar (.raucb.sig) produced
# by sign-images.sh at publish time.
RAUC_KEY_FILE  = "${MDMX_KEYS_DIR}/rsa.key"
RAUC_CERT_FILE = "${MDMX_KEYS_DIR}/rsa.cert.pem"

# Same trust anchor as the on-device keyring. Used by `rauc convert`
# during the (optional) casync path, and by `rauc bundle`'s cert-chain
# validation during signing. Not enabling casync so this is only a
# sanity check today, but harmless to set.
RAUC_KEYRING_FILE = "${MDMX_KEYS_DIR}/trust-bundle.pem"

python () {
    import os
    keys_dir = d.getVar('MDMX_KEYS_DIR')
    if not keys_dir:
        bb.fatal(
            "MDMX_KEYS_DIR is not set. Add\n"
            '    MDMX_KEYS_DIR = "${TOPDIR}/../keys/signing"\n'
            "to config/local.conf (or run ./sign-images.sh first, "
            "which generates the keys/signing/ directory)."
        )
    for basename in ("rsa.key", "rsa.cert.pem", "trust-bundle.pem"):
        p = os.path.join(keys_dir, basename)
        if not os.path.exists(p):
            bb.fatal(
                "RAUC signing material missing: %s\n"
                "Run './sign-images.sh' in the project root to generate it." % p
            )
}
