for_window [app_id="fish-terminal"] floating enable, resize set 1000 700, move scratchpad

bindsym Mod4+f [app_id="fish-terminal"] scratchpad show

exec /usr/bin/foot --app-id=fish-terminal /usr/bin/fish-monitor
