on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build image
    runs-on: self-hosted
    steps:
      - name: Checkout Repository incl. Submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Yocto with new config
        run: make build
