on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build image
    runs-on: self-hosted
    steps:
      - name: Checkout Repository inkl. Submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Zeige Dateistruktur (optional, zum Debuggen)
        run: ls -la
    
      - name: Starte Make
        run: make
