on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build image
    runs-on: self-hosted
    steps:
      - name: Install Yocto dependencies
        run: sudo apt-get update && sudo apt-get install -y chrpath diffstat gawk lz4
    
      - name: Checkout Repository incl. Submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Show datastructure
        run: ls -la
    
      - name: Init Yocto
        run: make init

      - name: Build Yocto
        run: make build
