on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build image
    runs-on: self-hosted
    steps:
      - name: Checkout Repository incl. Submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Init Yocto
        run: make init

      - name: Copy and paste config file
        run: cp ../config/local.conf conf/local.conf & cp ../config/bblayers.conf conf/bblayers.conf

      - name: Build Yocto
        run: make build
